### ISSUE TITLE
BadCard from Cardputer ERROR in TAB

### ISSUE THREAD

**Issue by PositivoDS** [VoidNoi/BadCard#7] opened 2024-07-18 10:10 UTC
Hi, Ivan! I have a problem with the badcard on the cardputer. The **TAB** key simply doesn't work. How can I fix it?

Sorry my english, i'm brazilian :)

Windows 10 pro
KeyBoard PT-br qwerty abnt

and when starting it for the first time in Windows, **it only works if you run a script first**, and only then does it detect a USB input and work normally.  thanks for answering.

**Comment by PositivoDS** [comment] 2024-07-18 10:12
Another thing, I downloaded it directly from **m5Launcher**. Think it's outdated there?

**Comment by VoidNoi** [comment] 2024-07-18 10:15
Have you tried adding a `DELAY 1000` at the start of the file?
The version from m5launcher should be the same as the one from m5burner, if it says v1.5.1 it's the latest version

**Comment by PositivoDS** [comment] 2024-07-18 10:20
yes, the latest version is v1.5.1. I tried putting delay 5000 before the "tabs" but never before everything. I will test and get back to you.

**Comment by VoidNoi** [comment] 2024-07-18 10:23
If it doesn't work please show me the whole script you're using so I can try to reproduce your problem

**Comment by PositivoDS** [comment] 2024-07-18 10:31
The 1000 ms delay before everything worked in terms of Windows not detecting the script initially. However, the TAB issue is still unresolved. I'll send a screenshot where the left side shows the original code, and the right side shows the adaptation I managed to make to get what I wanted to work.

I have another question. What would be the code for ALT + F4?

![tawetasefe](https://github.com/user-attachments/assets/249d2e99-0c31-4896-8c97-c970381a3f38)

**Comment by VoidNoi** [comment] 2024-07-18 10:48
You're right, the tab key doesn't seem to be doing what it should
> What would be the code for ALT + F4?

I believe ALT F4 should work but I haven't tried

**Comment by PositivoDS** [comment] 2024-07-18 10:49
I'll try then haha, thank you.

**Comment by VoidNoi** [comment] 2024-07-18 15:49
Should be fixed! https://github.com/VoidNoi/BadCard/commit/9a848d49b8f9275705e19744c3adc547cf015bd7
I also added a delay of 1000 by default to make sure you don't have to put it yourself in every file :)
~~I won't be updating the binaries yet because I'm about to release an update, I just have to check a few things and I'll update everything hopefully today!~~

**Comment by VoidNoi** [comment] 2024-07-18 19:05
I'm currently updating the binaries :)

**Comment by PositivoDS** [comment] 2024-07-18 19:27
You're amazing! Thank you for your attention. I'll be following everything :)
________________________________
De: Iván ***@***.***>
Enviado: quinta-feira, 18 de julho de 2024 13:49
Para: VoidNoi/BadCard ***@***.***>
Cc: PositivoDS ***@***.***>; Author ***@***.***>
Assunto: Re: [VoidNoi/BadCard] BadCard from Cardputer ERROR in TAB (Issue #7)


Should be fixed! 9a848d4<https://github.com/VoidNoi/BadCard/commit/9a848d49b8f9275705e19744c3adc547cf015bd7>
I also added a delay of 1000 by default to make sure you don't have to put it yourself in every file :)
I won't be updating the binaries yet because I'm about to release an update, I just have to check a few things and I'll update everything hopefully today!

**Comment by VoidNoi** [comment] 2024-07-18 19:34
Let me know if everything works on your end and I'll close this issue

**Comment by PositivoDS** [comment] 2024-07-18 19:49
Unfortunately, the "TAB" key is inserting a "+" sign.
________________________________
De: Iván ***@***.***>
Enviado: quinta-feira, 18 de julho de 2024 17:34
Para: VoidNoi/BadCard ***@***.***>
Cc: PositivoDS ***@***.***>; Author ***@***.***>
Assunto: Re: [VoidNoi/BadCard] BadCard from Cardputer ERROR in TAB (Issue #7)


Let me know if everything works on your end and I'll close this issue

**Comment by PositivoDS** [comment] 2024-07-18 19:50
Sorry, I would need to update to test, right?

________________________________
De: Iván ***@***.***>
Enviado: quinta-feira, 18 de julho de 2024 17:34
Para: VoidNoi/BadCard ***@***.***>
Cc: PositivoDS ***@***.***>; Author ***@***.***>
Assunto: Re: [VoidNoi/BadCard] BadCard from Cardputer ERROR in TAB (Issue #7)


Let me know if everything works on your end and I'll close this issue

**Comment by VoidNoi** [comment] 2024-07-18 19:52
Yes, you need to update to version 1.5.2

**Comment by PositivoDS** [comment] 2024-07-18 19:57
It worked! I updated and just tested it.
________________________________
De: Iván ***@***.***>
Enviado: quinta-feira, 18 de julho de 2024 17:53
Para: VoidNoi/BadCard ***@***.***>
Cc: PositivoDS ***@***.***>; Author ***@***.***>
Assunto: Re: [VoidNoi/BadCard] BadCard from Cardputer ERROR in TAB (Issue #7)


Yes, you need to update to version 1.5.2

**Comment by VoidNoi** [comment] 2024-07-18 19:59
Great, then I'll be closing this issue. Thank you for informing me about it!

**Closed as completed by VoidNoi** 2024-07-18 19:59 UTC
Labels: bug
